import random
import datetime

# let's personalize it 
name = input("What's your name? ")

# random daily affirmations - We all need a little pick me up, life is crazy enough

affirmations = [
    "Today is a fresh start.",
    "I am enough just as I am.",
    "I believe in my abilities and skills.",
    "I radiate confidence and self-respect.",
    "My challenges help me grow.",
    "I deserve love and kindness.",
    "I choose to focus on the positive.",
    "My potential is limitless.",
    "I am grateful for today.",
    "I am becoming the best version of myself.",
    "Every day, I learn and improve.",
    "I attract positivity and good energy.",
    "I trust in my journey.",
    "I am at peace with who I am.",
    "My mind is strong and resilient.",
    "I am worthy of happiness.",
    "I choose to see the good in people.",
    "I create my own happiness.",
    "I am capable of achieving my goals.",
    "My dreams are within reach.",
    "I am worthy of love and respect.",
    "I believe in myself and my abilities.",
    "I am enough just as I am.",
    "My self-worth is not defined by others.",
    "I choose to love and accept myself unconditionally.",
    "I radiate confidence and self-assurance.",
    "I am proud of who I am becoming.",
    "I honor my body, mind, and soul.",
    "My voice matters, and I deserve to be heard.",
     "I am beautiful inside and out.",
     "I am in charge of my own happiness.",
    "My thoughts create my reality, and I choose positivity.",
    "I radiate confidence, self-respect, and inner harmony.",
    "I am worthy of success and abundance.",
    "My challenges help me grow and become stronger.",
    "I am capable of achieving my dreams.",
    "Every day, I wake up with gratitude and excitement.",
    "My past does not define my future.",
    "I choose to see the good in every situation.",
    "My possibilities are endless.",
    "I attract happiness and joy into my life.",
    "I am grateful for the lessons that each day brings.",
    "I believe in myself and my abilities.",
    "I release all negativity and embrace positivity.",
    "I am full of love, hope, and gratitude.",
    "I am resilient, strong, and brave.",
    "I trust that everything is working out for my highest good.",
    "I am surrounded by love and everything is fine.",
    "My energy attracts good things into my life.",
    "I am exactly where I need to be at this moment.",
    "I am growing, evolving, and becoming my best self.",
    "I deserve happiness, love, and success.",
    "I am a magnet for abundance in all areas of my life.",
    "I have the power to create the life I desire.",
    "My dreams are valid, and I will achieve them.",
    "I am confident in my skills and talents.",
    "I welcome new opportunities with an open heart.",
    "I am fearless in the pursuit of my dreams.",
    "I choose joy over fear and love over doubt.",
    "I am worthy of all the good things life has to offer.",
    "My body, mind, and spirit are in perfect harmony.",
    "I radiate positivity and kindness wherever I go.",
    "I am at peace with my past and excited for my future.",
    "I am enough just as I am.",
    "I love and accept myself unconditionally.",
    "I deserve to be happy and to have a wonderful life.",
    "I trust myself to make the best decisions for me.",
    "I am grateful for every experience that has shaped me.",
    "Happiness is my choice, and I choose to be happy.",
    "I attract loving, positive people into my life.",
    "My life is filled with infinite possibilities.",
    "I am always learning and growing as a person.",
    "I am kind to myself and to others.",
    "I release all doubts and embrace my true potential.",
    "I am strong, capable, and resilient.",
    "I believe in the power of my dreams.",
    "I am thankful for the love and joy in my life.",
    "My heart is open to giving and receiving love.",
    "I am safe, protected, and guided by the universe.",
    "I let go of what I cannot control and embrace peace.",
    "I am creating a beautiful and successful life.",
    "I deserve success, and I am ready for it.",
    "Every day, I move closer to achieving my goals.",
    "I radiate confidence and positive energy.",
    "I trust in the timing of my life.",
    "I am grateful for this moment, and I embrace all that is to come.",
    "I am worthy of love and respect",
    "I believe in myself and my abilities",
    "I am enough just as I am",
    "My self-worth is not defined by others",
    "I choose to love and accept myself unconditionally",
    "I radiate confidence and self-assurance",
    "I am proud of who I am becoming",
    "I honor my body, mind, and soul",
    "My voice matters, and I deserve to be heard",
    "I am beautiful inside and out",
    "I am a unique and valuable person",
    "My opinions are valid, and my thoughts matter",
    "I trust myself to make the right decisions",
    "I attract positive and supportive people",
    "I release all self-doubt and embrace my greatness",
    "My happiness comes from within",
    "I celebrate my progress, no matter how small",
    "I am proud of myself and how far I have come",
    "I deserve kindness, including my own",
    "I am constantly evolving into the best version of myself",
    "I am capable of achieving my dreams",
    "Every challenge is an opportunity to grow",
    "I am strong, smart, and driven",
    "I am disciplined and focused on my goals",
    "I attract success and abundance",
    "I am fearless in pursuing my dreams",
    "I have everything I need to succeed",
    "I am always learning and improving",
    "I turn obstacles into stepping stones",
    "I am open to new opportunities",
    "I take action towards my goals every day",
    "My work is valuable, and I make a difference",
    "I trust that everything is unfolding for my highest good",
    "I embrace failure as a learning experience",
    "I am resilient, and I overcome setbacks with ease",
    "I stay committed to my dreams and goals",
    "Success flows to me effortlessly",
    "My mindset determines my success, and I choose positivity",
    "I create my own opportunities",
    "My dreams are possible, and I will achieve them",
    "I choose happiness in every moment",
    "I find joy in the little things",
    "My life is filled with positivity and joy",
    "I release all negativity and welcome peace",
    "I radiate happiness, and it returns to me",
    "I am in control of my emotions",
    "I am grateful for this beautiful life",
    "I focus on the present moment and enjoy it",
    "I see the good in every situation",
    "My heart is full of love and joy",
    "I welcome happiness into my life",
    "I have the power to create a happy life",
    "I choose thoughts that bring me happiness",
    "Every day is a fresh start to be happy",
    "I let go of worries and embrace joy",
    "I attract positive experiences into my life",
    "My life is filled with laughter and fun",
    "I wake up excited for the day ahead",
    "I deserve happiness and fulfillment",
    "I choose to see the beauty in the world around me",
    "Money flows easily into my life",
    "I am open to receiving unlimited abundance",
    "Wealth and success come naturally to me",
    "I attract financial prosperity effortlessly",
    "I am worthy of financial freedom",
    "My income is constantly increasing",
    "I make wise financial decisions",
    "I am financially independent and secure",
    "I have the power to create wealth",
    "Abundance is all around me",
    "I attract opportunities for wealth and success",
    "I am grateful for the money I have",
    "I deserve a life of abundance",
    "Money is a tool that allows me to live my dreams",
    "Every dollar I spend comes back to me multiplied",
    "My hard work brings financial rewards",
    "I welcome wealth and prosperity into my life",
    "I am open to new streams of income",
    "My financial situation is improving every day",
    "I release any limiting beliefs about money",
    "My body is healthy, strong, and full of energy",
    "I take care of my body, and it takes care of me",
    "I choose to nourish my body with healthy choices",
    "I love and appreciate my body",
    "My mind is clear, and my body is vibrant",
    "I am grateful for my health",
    "I honor my body by treating it with love and respect",
    "I am healing, and my body is getting stronger",
    "I prioritize self-care and well-being",
    "I listen to my body’s needs",
    "My body deserves love and appreciation",
    "I release stress and embrace peace",
    "Every breath I take fills me with energy and vitality",
    "I enjoy moving my body and staying active",
    "I sleep peacefully and wake up refreshed",
    "I am in perfect health",
    "My mind and body are in harmony",
    "I make choices that support my well-being",
    "I am kind to myself and my body",
    "I radiate health, happiness, and energy",
    "I am surrounded by love and positivity",
    "I attract loving and supportive relationships",
    "I give and receive love freely",
    "My relationships are filled with love and trust",
    "I deserve healthy, happy relationships",
    "Love flows freely to and from me",
    "I create deep and meaningful connections",
    "I am open to giving and receiving love",
    "I am a magnet for loving relationships",
    "I communicate openly and honestly",
    "I release toxic relationships with love and peace",
    "My heart is open to love",
    "I am worthy of unconditional love",
    "I attract people who uplift and support me",
    "I am kind, loving, and compassionate",
    "I trust the universe to bring the right people into my life",
    "I choose relationships that bring me joy",
    "I am grateful for the love in my life",
    "I give love freely without expectation",
    "My heart is filled with gratitude and love",
    "I matter in the grand scheme of things, I am part of a beautiful puzzle that makes life beautiful"

]

# Timestamp to help with correct salutation 
current_hour = datetime.datetime.now().hour

# Determine salutation based on time
if current_hour < 12:
    salutation = "Good morning"
elif 12 <= current_hour < 17:
    salutation = "Good afternoon"
else:
    salutation = "Good evening"

# Picking a random affirmation with every refresh
todays_affirmation = random.choice(affirmations)

# Display the personalized affirmation
print(f"🌟 {salutation}, {name}! Here’s your daily affirmation 🌟")
print(todays_affirmation)
